/**
 * @description       : 
 * @author            : Kenneth Ray Sr Salesforce Developer. 
 * @group             : 
 * @last modified on  : 06-02-2022
 * @last modified by  : Kenneth Ray, Sr Salesforce Developer. 
**/

/** PLEASE LEAVE COMMENTED 
 * 1. To ensure users have access to approved data, ensure sharing is enforced.
 * 2. To use method within LWC, add correct annotation to expose method to LWC framework.
 * 3. Create query to populate datatable. Conductor will provide object and list of fields.
 * */
public class Quiz001_Controller {

    public static void methodOne(){
        try {
            return;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}
